### ISSUE TITLE
About the timing of releasing implementation codes

### ISSUE THREAD

**Issue by TensorsSun** [lntzm/MESM#1]
Hi,
First, thanks for making your code opensource on github.
Could you tell more about the releasing timing of the implementation codes, like do you have any plan when to upload it?
I'd appreciate it if you could give a more specific date, thanks.

**Comment by lntzm** [comment]
Hello, thanks for your attention.
We plan to release our code around the time of the AAAI 2024 conference, at the end of February.

**Comment by TensorsSun** [comment]
Thank you for replying so quickly.
Looking forward to your work. Best wishes to you.

**Comment by TensorsSun** [comment]
![微信图片_20240130221647](https://github.com/lntzm/MESM/assets/48124968/bd4addbd-e96b-4a8d-add0-e76cb18b1781)
Hello, I would like to know what the meaning of "re-implement under the same training scheme" here? Is it because there is no mAP@0.5/0.75/avg in the original paper?

**Comment by lntzm** [comment]
Yes, they only report R1@0.5 and R1@0.7 in their paper, the results of mAP are lacking. Therefore, we re-implement their methods and use their training settings to get mAP. As you can see, our re-implemented R1 results are similar to what they reported.

**Comment by TensorsSun** [comment]
![微信图片_20240131234651](https://github.com/lntzm/MESM/assets/48124968/7dcc0c16-2d6c-4dec-8165-7baa28980033)
For fair comparison, should the three methods in Table 3 also be "re-implemented under the same training scheme"? Because they trained together moment retrieval and highlight detection on the QVHighlights data set, but your method only targets moment retrieval.

**Comment by lntzm** [comment]
Since they report both R1 and mAP, we do not need to reimplement them.
They use the highlight detection labels for supervision, and we follow them for fair comparison. Specifically, we replace the Eq 6 in our paper to the Eq 6 in QD-DETR for QVHighlights dataset.

**Comment by lntzm** [comment]
Hi, the code is released now, more configs and trained models will come soon.

**Comment by YunjinYeung** [comment]
Hi!  thank you very much for sharing your source code on Github.  Could you share more about the configs or trained scripts about the QVHighlights? thanks.

**Comment by lntzm** [comment]
Yes, I plan to. But I am a little busy now and I have even not completed my README :(.
Also, the results on QVHighlights are on another machine and the machine is expired for me now and I lost the trained data... I will try to re-run it and release the results.
