### ISSUE TITLE
download the pretrained_models/clip_text_encoder.pth

### ISSUE THREAD

**Issue by byman577** [lntzm/MESM#2]
Hello, I encountered some problems when trying to reproduce this interesting work. Can you tell me where I can download the pretrained_models/clip_text_encoder.pth file?

**Comment by lntzm** [comment]
It is the official CLIP text encoder. You can just download CLIP model by `import clip; clip.load('ViT-B/32', device)` and drop the visual part.

**Comment by byman577** [comment]
Thank you for your answer！ In addition, I would like to ask how to obtain the glove.pkl file in the project. I tried to use the glove.840B.300d.pkl file but the code reported an error.

**Comment by lntzm** [comment]
I have introduced the glove.pkl for the Charades-STA dataset in [README.md](https://github.com/lntzm/MESM?tab=readme-ov-file#charades-features).  We follow [CPL](https://github.com/minghangz/cpl) to obtain `glove.pkl`. 
In fact, `glove.pkl` is not a must for this project. You can set the arg `load_vocab_pkl` False, and set the arg `text_model_path` to the path of `glove.840B.300d.txt` or `glove.6B.300d.txt`. Usually, you will get similar results.
